// Pedidos/page.tsx
import { Metadata } from "next";
import Pedidos from "./components/pedidos";

export const metadata: Metadata = {
  title: "Pedidos - FORNALHA HAMBURGUERIA E PETISCARIA Frederico Westphalen",
  description: "Generated by create next app",
};

export default function Page() {
  return <Pedidos />;
}
