import React from 'react';
import SectionsMenu from './components/SectionsMenu';
import Banner from './components/banner';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "FORNALHA HAMBURGUERIA E PETISCARIA - Card&#225;pio FORNALHA HAMBURGUERIA E PETISCARIA Frederico Westphalen",
  description: "Generated by create next app",
};

const App: React.FC = () => {
  return (
      <div>
        <Banner/>
        <SectionsMenu />
      </div>
  );
};

// Developed by primerdev - contato.primerdev@gmail.com

export default App;
