import { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
  title: "Campanhas - FORNALHA HAMBURGUERIA E PETISCARIA Frederico Westphalen",
  description: "Generated by create next app",
};

const CampanhasPage: React.FC = () => {
  return (
    <div className="container mx-auto p-4 text-black bg-white max-w-[1200px] max-h-[100%]">
      <h1 className="text-3xl font-bold mb-4">Campanhas de Fidelidade</h1>
      <p>No momento, não há campanhas de fidelidade ativas. Fique ligado para futuras promoções!</p>
    </div>
  );
};

export default CampanhasPage;
